version: 2
registries:
  spring-milestones:
    type: maven-repository
    url: https://repo.spring.io/milestone
updates:
  - package-ecosystem: gradle
    target-branch: main
    directory: /
    schedule:
      interval: weekly
      time: '03:00'
      timezone: Etc/UTC
    labels:
      - 'type: dependency-upgrade'
    registries:
      - spring-milestones
    ignore:
      - dependency-name: com.nimbusds:nimbus-jose-jwt
      - dependency-name: org.python:jython
      - dependency-name: org.apache.directory.server:*
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: com.gradle.enterprise
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: npm
    target-branch: main
    directory: /docs
    schedule:
      interval: weekly
      time: '08:47'
